I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/lev0_eng.rpy", line 14, in script
    init python:
  File "game/lev0_eng.rpy", line 15, in <module>
    text_list = list(random.shuffle([[0.6, 0.05], [0.6, 0.5], [0.6, 0.2]]))
TypeError: 'NoneType' object is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/lev0_eng.rpy", line 14, in script
    init python:
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/lev0_eng.rpy", line 15, in <module>
    text_list = list(random.shuffle([[0.6, 0.05], [0.6, 0.5], [0.6, 0.2]]))
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\python.py", line 799, in __init__
    list.__init__(self, *args)
TypeError: 'NoneType' object is not iterable

Windows-8-6.2.9200
Ren'Py 7.1.1.929
 
Sun Dec 02 22:28:10 2018
